[build]
  builder = "DOCKERFILE"
  dockerfilePath = "apps/api/Dockerfile.prod"
  dockerContext = "."

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"

